allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@workflow/astro@4.0.12'
  - '@workflow/builders@4.1.2'
  - '@workflow/cli@4.3.1'
  - '@workflow/core@4.6.1'
  - '@workflow/errors@4.1.5'
  - '@workflow/nest@4.0.13'
  - '@workflow/next@4.1.1'
  - '@workflow/nitro@4.1.3'
  - '@workflow/nuxt@4.0.13'
  - '@workflow/rollup@4.0.12'
  - '@workflow/sveltekit@4.0.12'
  - '@workflow/utils@4.1.4'
  - '@workflow/vite@4.0.12'
  - '@workflow/web@4.1.13'
  - '@workflow/world-local@4.2.2'
  - '@workflow/world-vercel@4.5.1'
  - workflow@4.6.1
